# Generated by Django 5.2.4 on 2025-08-14 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('therapists', '0002_remove_therapist_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='therapist',
            name='country',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='therapist',
            name='department',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='therapist',
            name='district',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='therapist',
            name='province',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
