name: Validación Frontend

on:
  push:
      branches: [main]  # Puedes cambiar 'main' por otra rama si la usas

jobs:
  validar:
        runs-on: ubuntu-latest

        steps:      
        - name: Clonar el repositorio
          uses: actions/checkout@v4

        - name: Verificar Codigo HTML
          run: |
            npm install -g htmlhint
            htmlhint html/index.html || exit 1

        - name: Verificar Codigo JavaScript
          run: |
            npm install -g eslint@8
            eslint js/script.js  exit 1

        - name: Verificar Codigo CSS
          run: |
            npm install -g stylelint stylelint-config-standard
            echo '{ "extends": "stylelint-config-standard" }' > .stylelintrc.json
            stylelint css/style.css || exit 1